//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> credits { get; set; }
        public string major { get; set; }
        public Nullable<int> dept { get; set; }
    }
}
